version: '3'

services:
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # command: sh -c "apachectl -D FOREGROUND"
    volumes:
      - ./server:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - tododb

  tododb:
    env_file: .env
    image: mysql:5.7
    container_name: tododb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: $DB_TZ
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33030:3306
